import { useState, useEffect, useCallback } from "react";
import { supabase, getFollowers, getFollowing, getFriends, getPendingRequests, followUser, unfollowUser, acceptFriendRequest, rejectFriendRequest } from "../../supabaseClient.js";

export function FriendsTab() {
  const [activeTab,setActiveTab]=useState("friends"); const [lists,setLists]=useState({friends:[],followers:[],following:[],requests:[]}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(null);
  const loadProfiles=useCallback(async(ids)=>{const u=[...new Set((ids||[]).filter(Boolean))]; if(!u.length)return []; const {data,error}=await supabase.from("profiles").select("user_id,display_name,handle,flag,avatar_url,bio").in("user_id",u); if(error)throw error; return data||[]},[]);
  const load=useCallback(async()=>{setLoading(true);try{const [{data:f},{data:fol},{data:fin},{data:req}]=await Promise.all([getFriends(),getFollowers(),getFollowing(),getPendingRequests()]); const [friends,followers,following,reqProfiles]=await Promise.all([loadProfiles(f),loadProfiles(fol),loadProfiles(fin),loadProfiles((req||[]).map(r=>r.follower_id))]); const map=new Map(reqProfiles.map(p=>[p.user_id,p])); setLists({friends,followers,following,requests:(req||[]).map(r=>({...map.get(r.follower_id),requester_id:r.follower_id})).filter(x=>x.user_id)});}catch(e){console.error("Erreur communauté",e)}finally{setLoading(false)}},[loadProfiles]);
  useEffect(()=>{load()},[load]);
  const act=async(key,fn)=>{setBusy(key);try{await fn();await load()}catch(e){console.error(e)}finally{setBusy(null)}};
  const tabs=[{id:"friends",label:"👫 Amis"},{id:"followers",label:"📥 Abonnés"},{id:"following",label:"📤 Abonnements"},{id:"requests",label:"📩 Demandes"}];
  const render=(u,type)=>{if(!u)return null; const id=u.user_id; return <div key={id} className="flex items-center justify-between p-3 bg-gray-800/50 rounded-xl"><div className="flex items-center gap-3">{u.avatar_url?<img src={u.avatar_url} alt="" className="w-10 h-10 rounded-full object-cover"/>:<span className="text-2xl">{u.flag||"🌍"}</span>}<div><p className="font-semibold text-white">{u.display_name||"Membre"}</p><p className="text-sm text-gray-400">{u.handle?`@${String(u.handle).replace(/^@/,"")}`:"@membre"}</p></div></div><div>{type==="followers"&&<button disabled={busy===id} onClick={()=>act(id,()=>followUser(id))} className="bg-blue-600 text-white px-4 py-1.5 rounded-full text-sm">{busy===id?"…":"+ Suivre"}</button>}{type==="following"&&<button disabled={busy===id} onClick={()=>act(id,()=>unfollowUser(id))} className="bg-gray-700 text-gray-300 px-4 py-1.5 rounded-full text-sm">{busy===id?"…":"✓ Suivi"}</button>}{type==="requests"&&<div className="flex gap-2"><button disabled={busy===id} onClick={()=>act(id,()=>acceptFriendRequest(u.requester_id))} className="bg-green-600 text-white px-3 py-1.5 rounded-full">✓</button><button disabled={busy===id} onClick={()=>act(id,()=>rejectFriendRequest(u.requester_id))} className="bg-red-600 text-white px-3 py-1.5 rounded-full">✕</button></div>}</div></div>};
  const list=lists[activeTab]||[]; return <div className="p-4"><h2 className="text-2xl font-bold text-white mb-4">👥 Communauté</h2><div className="flex gap-2 mb-6 overflow-x-auto pb-2">{tabs.map(t=><button key={t.id} onClick={()=>setActiveTab(t.id)} className={`px-4 py-2 rounded-full text-sm font-medium whitespace-nowrap ${activeTab===t.id?"bg-blue-600 text-white":"bg-gray-800/50 text-gray-400"}`}>{t.label}</button>)}</div>{loading?<div className="text-center py-8 text-gray-400">Chargement...</div>:!list.length?<div className="text-center py-12 text-gray-400">{activeTab==="requests"?"Aucune demande en attente.":activeTab==="friends"?"Aucun ami pour le moment.":"Aucun utilisateur."}</div>:<div className="space-y-2">{list.map(u=>render(u,activeTab))}</div>}</div>
}
